INSERT INTO Board (title, content, thumbnail, fileUrl, showCount)
VALUES ('ROSÉ & Bruno Mars - APT. (Official Music Video)',
        'ROSÉ & Bruno Mars - APT. (Official Music Video)',
        'https://i.ytimg.com/vi/ekr2nIex040/hq720.jpg?sqp=-oaymwEpCNAFEJQDSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLD4TMcWEAI1l4Q-vf857ofF4wRGuA',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/ekr2nIex040?si=3WsuEGwS3ss-rtJT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
       95),
       ('aespa 에스파 Whiplash MV', 'aespa 에스파 Whiplash MV',
        'https://i.ytimg.com/vi/jWQx2f-CErU/hq720.jpg?sqp=-oaymwEpCNAFEJQDSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLBZrF4QKFa6sKzk1ywB_Jv-BBNmTg',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/jWQx2f-CErU?si=aiQ3CfAF3NM7-DHt" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
       0),
       ('BABYMONSTER - ‘CLIK CLAK’ PERFORMANCE VIDEO', 'BABYMONSTER - ‘CLIK CLAK’ PERFORMANCE VIDEO',
        'https://i.ytimg.com/vi/frV8cZ_yA_4/hq720.jpg?sqp=-oaymwEpCNAFEJQDSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLBwbqXZioWnLy5qqUemz47taP84bg',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/frV8cZ_yA_4?si=cxWto5Gz1CmdVAjz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
       40),

       ('LE SSERAFIM (르세라핌) ''CRAZY'' OFFICIAL MV', 'LE SSERAFIM (르세라핌) ''CRAZY'' OFFICIAL MV',
        'https://i.ytimg.com/vi/n6B5gQXlB-0/hq720.jpg?sqp=-oaymwEpCNAFEJQDSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLCOmaTicI-O9RGsAdyX5YXSBNS8Ng',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/n6B5gQXlB-0?si=8PUHkEq3OMt06Ph7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
       70),
       ('KATSEYE (캣츠아이) "Touch" Official MV', 'Content for board 5',
        'https://i.ytimg.com/vi/l9CZykYZkOQ/hq720.jpg?sqp=-oaymwEpCNAFEJQDSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLCf-iBBmntE91JcQMjucQ8vLaQGaQ',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/l9CZykYZkOQ?si=SJdMHDHvQVLghAHE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
       14481),

       ('[MV] Kik5o(키코) _ NIGHTMARE', '[MV] Kik5o(키코) _ NIGHTMARE',
        'https://i.ytimg.com/vi/gexuwVK4_vE/hq720.jpg?sqp=-oaymwEpCNAFEJQDSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLCCyp54QzBTgXmeLgfCE5hiknR-lg',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/gexuwVK4_vE?si=W7xBfN5c14X9Sztm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
       7),
       ('MEOVV - ‘MEOW’ M/V', 'MEOVV - ‘MEOW’ M/V',
        'https://i.ytimg.com/vi/jpLHg-AsQV0/hq720.jpg?sqp=-oaymwEpCNAFEJQDSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLCc68gniMisClXSrXv73VMcbMScng',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/jpLHg-AsQV0?si=WycrnA5UeNNYBjyL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
       0),
       ('BTS (방탄소년단) ''Butter'' Official MV', 'BTS (방탄소년단) ''Butter'' Official MV',
        'https://i.ytimg.com/vi/WMweEpGlu_U/hq720.jpg?sqp=-oaymwEpCNAFEJQDSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLCy6ySry0yLfe0hXkEAqTSD4DFpqg',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/WMweEpGlu_U?si=xPWHFN1TeResqOL0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
       1),
       ('BTS (방탄소년단) ''작은 것들을 위한 시 (Boy With Luv) (feat. Halsey)'' Official MV', 'BTS (방탄소년단) ''작은 것들을 위한 시 (Boy With Luv) (feat. Halsey)'' Official MV',
        'https://i.ytimg.com/vi/XsX3ATc3FbA/hq720.jpg?sqp=-oaymwEpCNAFEJQDSFryq4qpAxsIARUAAIhCGAHYAQHiAQwIHBACGAYgATgBQAE=&rs=AOn4CLBVKRAKuW7q5BiIY-Fz0e_7UXBgxw',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/XsX3ATc3FbA?si=j-emaYUcuNqdC5qN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
       0);