CREATE TABLE IF NOT EXISTS Board
(
    id        BIGINT PRIMARY KEY AUTO_INCREMENT,
    title     TEXT NOT NULL,
    content   TEXT NOT NULL,
    thumbnail TEXT NOT NULL,
    fileUrl TEXT NOT NULL,
    showCount BIGINT NOT NULL default 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);