services:
  db:
    image: mariadb:10.4.13
    container_name: tmp
    ports:
      - 33306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bbs
      - LANG=C.UTF-8
    volumes:
      - "data:/var/lib/mysql"
      - "./db/ddl.sql:/docker-entrypoint-initdb.d/1-init.sql"
      - "./db/data.sql:/docker-entrypoint-initdb.d/2-init.sql"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --character-set-filesystem=utf8
      - --concurrent-insert=AUTO
      - --connect-timeout=10
volumes:
  data:
    driver: local